language: php

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - env: title="PHP 5.6"
      php: 5.6
      install:
        - composer install -d 2.3 --no-interaction -o
      script:
        - composer run-script -d 2.3 tests

    - env: title="PHP 7.0"
      php: 7.0
      install:
        - composer install -d 2.3 --no-interaction -o
      script:
        - composer run-script -d 2.3 tests

    - env: title="PHP 7.1"
      php: 7.1
      install:
        - composer install -d 2.3 --no-interaction -o
        - composer install -d 2.4 --no-interaction -o
        - composer install -d 3.0 --no-interaction -o
      script:
        - composer run-script -d 2.3 tests
        - composer run-script -d 2.4 tests
        - composer run-script -d 3.0 tests

    - env: title="PHP 7.2"
      php: 7.2
      install:
        - composer install -d 2.4 --no-interaction -o
        - composer install -d 3.0 --no-interaction -o
      script:
        - composer run-script -d 2.4 tests
        - composer run-script -d 3.0 tests

    - env: title="PHP 7.3"
      php: 7.3
      install:
        - composer install -d 2.4 --no-interaction -o
        - composer install -d 3.0 --no-interaction -o
      script:
        - composer run-script -d 2.4 tests
        - composer run-script -d 3.0 tests

    - env: title="PHP 7.4"
      php: 7.4
      install:
        - composer install -d 2.4 --no-interaction -o
        - composer install -d 3.0 --no-interaction -o
      script:
        - composer run-script -d 2.4 tests
        - composer run-script -d 3.0 tests

    - env: title="PHP 8.0"
      php: 8.0
      install:
        - composer install -d 3.0 --no-interaction -o
        - composer install -d 3.1 --no-interaction -o
      script:
        - composer run-script -d 3.0 tests
        - composer run-script -d 3.1 tests

    - env: title="PHP 8.1"
      php: 8.1
      install:
        - composer install -d 3.0 --no-interaction -o
        - composer install -d 3.1 --no-interaction -o
        - composer install -d 3.2 --no-interaction -o
      script:
        - composer run-script -d 3.0 tests
        - composer run-script -d 3.1 tests
        - composer run-script -d 3.2 tests

    - env: title="PHP 8.2"
      php: 8.2
      install:
        - composer install -d 3.1 --no-interaction -o
        - composer install -d 3.2 --no-interaction -o
      script:
        - composer run-script -d 3.1 tests
        - composer run-script -d 3.2 tests

    - env: title="PHP 8.3"
      php: 8.3
      install:
        - composer install -d 3.1 --no-interaction -o
        - composer install -d 3.2 --no-interaction -o
      script:
        - composer run-script -d 3.1 tests
        - composer run-script -d 3.2 tests

    - env: title="PHP 8.4"
      php: 8.4
      install:
        - composer install -d 3.1 --no-interaction -o
        - composer install -d 3.2 --no-interaction -o
      script:
        - composer run-script -d 3.1 tests
        - composer run-script -d 3.2 tests

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
