name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # PHP 7.1 - supports 2.3, 2.4, 3.0
          - php: '7.1'
            version: '2.3'
          - php: '7.1'
            version: '2.4'
          - php: '7.1'
            version: '3.0'

          # PHP 7.2 - supports 2.3, 2.4, 3.0
          - php: '7.2'
            version: '2.3'
          - php: '7.2'
            version: '2.4'
          - php: '7.2'
            version: '3.0'

          # PHP 7.3 - supports 2.4, 3.0 (2.3 requires PHP <7.3)
          - php: '7.3'
            version: '2.4'
          - php: '7.3'
            version: '3.0'

          # PHP 7.4 - supports 2.4, 3.0
          - php: '7.4'
            version: '2.4'
          - php: '7.4'
            version: '3.0'

          # PHP 8.0 - supports 3.0, 3.1
          - php: '8.0'
            version: '3.0'
          - php: '8.0'
            version: '3.1'

          # PHP 8.1 - supports 3.0, 3.1
          - php: '8.1'
            version: '3.0'
          - php: '8.1'
            version: '3.1'

          # PHP 8.2 - supports 3.1, 3.2
          - php: '8.2'
            version: '3.1'
          - php: '8.2'
            version: '3.2'

          # PHP 8.3 - supports 3.1, 3.2
          - php: '8.3'
            version: '3.1'
          - php: '8.3'
            version: '3.2'

          # PHP 8.4 - supports 3.1, 3.2
          - php: '8.4'
            version: '3.1'
          - php: '8.4'
            version: '3.2'

    name: PHP ${{ matrix.php }} / ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction --optimize-autoloader
        working-directory: ${{ matrix.version }}

      - run: composer tests
        working-directory: ${{ matrix.version }}

      - if: failure()
        run: for i in $(find tests -name '*.actual'); do echo "--- $i"; cat "$i"; echo; done
        working-directory: ${{ matrix.version }}
